stages:
- stage: stage1
    displayName: "checking output"
    pool:
    vmImage: 'ubuntu-16.04'
  jobs:
  - job: job1
    steps:
    - bash: echo "this is first stage"
- stage: stage2
    displayName: "checking 2nd stage"
    pool:
    vmImage: 'ubuntu-16.04'
  jobs:
  - job: job2
    steps:
    - bash: echo "this 2nd stage"